Pbday/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),
    # path('home/', include('myapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('friends', views.friends, name='friends'),
    path('family', views.family, name='family'),
    path('lovelies', views.lovelies, name='lovelies'),
    path('videos', views.showvideo, name='videos'),
    path('found', views.searchFound, name='new_search'),
    path('<name>', views.detailView, name='detail')
    #path('<key>', views.videodetailview, name='vdetail')
]

myapp/models.py
from django.db import models


# Create your models here.
class Friends(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="myapp/static/myapp/images/", blank=True, null=True)
    sideways = models.BooleanField(default=False)
    message = models.TextField(max_length=5000, verbose_name='', blank=True, null=True)


class Family(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="myapp/static/myapp/images/", blank=True, null=True)
    sideways = models.BooleanField(default=False)
    message = models.TextField(max_length=5000, verbose_name='', blank=True, null=True)


class Lovelies(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="myapp/static/myapp/images/", blank=True, null=True)
    sideways = models.BooleanField(default=False)
    message = models.TextField(max_length=5000, verbose_name='', blank=True, null=True)


class Video(models.Model):
    name = models.CharField(max_length=50)
    key = models.IntegerField(blank=True, null=True)
    image = models.ImageField(upload_to="myapp/static/myapp/images/", blank=True, null=True)
    video_file = models.FileField(upload_to="myapp/static/myapp/videos/", null=True, blank=True)
    videoflag = models.BooleanField(default=False)

myapp/views.py
import base64
from django.shortcuts import render
from .models import Friends, Family, Lovelies, Video
from django.contrib.postgres.lookups import Unaccent
#import playsound


# Create your views here.

def home(request):
    #playsound.playsound('myapp/static/myapp/media/H2.mp3', False)
    return render(request, "myapp/home.html")


def friends(request):
    model = Friends
    friendsData = []

    for f in Friends.objects.all().order_by('name'):
        image_url = f.image.url
        friendsData.append((f.name, image_url[7:], f.message))

    stuff_to_frontend = {
        'friends': friendsData,
    }
    return render(request, "myapp/friends.html", stuff_to_frontend)


def family(request):
    model = Family
    familyData = []

    for f in Family.objects.all().order_by('name'):
        image_url = f.image.url
        familyData.append((f.name, image_url[7:], f.message))
    stuff_to_frontend = {
        'family': familyData,
    }
    return render(request, "myapp/family.html", stuff_to_frontend)


def lovelies(request):
    model = Lovelies
    loveliesData = []

    for l in Lovelies.objects.all().order_by('name'):
        image_url = l.image.url
        loveliesData.append((l.name, image_url[7:], l.message))

    stuff_to_frontend = {
        'lovelies': loveliesData,
    }
    return render(request, "myapp/lovelies.html", stuff_to_frontend)


def searchFound(request):
    name = request.POST.get('searchwindow')
    print(name)
    data = []
    displaylist = []

    # try:
    #     for f in Friends.objects.get(name__startswith=name):
    #         data.append((f.name, f.image.url[7:]))
    #         print(f)
    #     print(data)
    # except:
    #     print("No Friends found")
    #
    # try:
    #     data.append((Family.objects.get(name__startswith=name)))
    # except:
    #     print("No Family found")
    #
    # try:
    #     data.append((Lovelies.objects.get(name__startswith=name)))
    # except:
    #     print("No Lovelies found")
    #
    # length = len(data)
    #
    # for i in range(length):
    #     displaylist.append((data[i].name, data[i].image.url[7:]))

    if Friends.objects.filter(name=name):
        data = (Friends.objects.get(name=name))
    elif Family.objects.filter(name=name):
        data = (Family.objects.get(name=name))
    elif Lovelies.objects.filter(name=name):
        data = (Lovelies.objects.get(name=name))

    if data:
        # if True:
        message = data.message
        image_path = data.image.url[1:]
    else:
        message = "................."
        image_path = ('myapp/static/myapp/images/main.png')
        # image_path = ('/home/pi/PythonProg/Pbday/myapp/static/myapp/images/main.png')

    with open(image_path, "rb") as image_file:
        image_data = base64.b64encode(image_file.read()).decode('utf-8')

    stuff_to_frontend = {
        'name': name,
        'photo': image_data,
        'message': message
    }

    # stuff_to_frontend = {
    #     'length': length,
    #     'displaylist': displaylist,
    # }

    return render(request, "myapp/searchfound.html", stuff_to_frontend)


def detailView(request, name):
    data = []

    if name == "1" or name == "2" or name == "3":
        vdetail = videodetailview(name)
        return render(request, "myapp/videodetail.html", vdetail)
    else:

        if Friends.objects.filter(name=name):
            data = (Friends.objects.get(name=name))
        elif Family.objects.filter(name=name):
            data = (Family.objects.get(name=name))
        elif Lovelies.objects.filter(name=name):
            data = (Lovelies.objects.get(name=name))

        if data:
            message = data.message
            image_path = data.image.url[1:]
            image_sideways = data.sideways

        else:
            message = "................."
            image_sideways = False
            image_path = ('myapp/static/myapp/images/main.png')

        with open(image_path, "rb") as image_file:
            image_data = base64.b64encode(image_file.read()).decode('utf-8')

        # print(image_data)
        detail = {
            'name': name,
            'photo': image_data,
            'message': message,
            'sideways': image_sideways
        }

        return render(request, "myapp/detail.html", detail)


def showvideo(request):
    model = Video
    videodata = []

    for v in Video.objects.all().order_by('name'):
        image_url = v.image.url
        videodata.append((v.name, v.key, image_url[7:]))

    stuff_to_frontend = {
        'videodata': videodata,
    }
    return render(request, "myapp/Videos.html", stuff_to_frontend)

def videodetailview(key):
    data = []
    vdetail={}
    video_path = "myapp/static/myapp/videos/Jiana.mp4"
    video_present = False

    if Video.objects.filter(key=key):
        data = (Video.objects.get(key=key))

    try:
        if data:

            image_path = data.image.url[1:]
            with open(image_path, "rb") as image_file:
                image_data = base64.b64encode(image_file.read()).decode('utf-8')
            video_present = data.videoflag
            video_path = data.video_file.url[1:]
    except:
        print("Error")
    # print(image_data)

    vdetail = {
        'name': data.name,
        'key': data.key,
        'video_path': video_path,
        'photo' : image_data,
        'video_present': video_present
    }

    return vdetail

myapp/templates/myapp/Videos.html
{% extends "myapp/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<body>
{% block content %}
{% include "myapp/base.html" %}
<div class="container nav-wrapper">
    <h4 class = "green-text" align = "center">The cutest of all.....</h4>
</div>
<div class="container nav-wrapper">
    <div class="row">
        {% for v in videodata %}
            <div class="col s12 m4">
                <div class="card small">
                    <div class="card-image waves-effect waves-block waves-light" >
                        <a href = "{% url 'myapp:detail' v.1%}"><img class="activator" src={{v.2}}></a>
                    </div>
                    <div class="card-content">
                        <a href = "{% url 'myapp:detail' v.1%}"><span class="card-title activator grey-text text-darken-4">{{v.0}}</span></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}
</body>

</html>

myapp/templates/myapp/base.html
{% load static %}


<!DOCTYPE html>
<html>


<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="{% static 'myapp/css/materialize.css' %}">
    <!--      <link rel="stylesheet" href="mydb/css/materialize.min.css"  media="screen,projection"/>-->
    <script type="text/javascript" src="{% static 'myapp/js/build-table.js' %} "></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--<meta http-equiv="refresh" content="5">-->
</head>

<body style="background-color:black; ">
<!--style="background-color:black; "-->
<!--class="black"-->

{% block content %}
<nav class="black" style="font-size:24">
    <div class="container nav-wrapper" >
        <ul id="nav-mobile" class="left" >
            <li id='home'><a href="/">Home</a></li>
            <li id='friends'><a href="/friends">Friends</a></li>
            <li id='family'><a href="/family">Family</a></li>
            <li id='lovelies'><a href="/lovelies">Lovelies</a></li>
            <li id='videos'><a href="/videos">Cute Wishes</a></li>
        </ul>

        <div class="input-field right black" >
            <form action = "{% url 'myapp:new_search'%}"  method="post">
            {% csrf_token %}
                <input style = "color:white" class = "black" id="search" type="search" name ="searchwindow" placeholder="Search">
            </form>
        </div>
    </div>

</nav>
<!--
<audio autoplay>
    <source src="/static/myapp/media/H2.mp3" type="audio/mp3">
</audio>
-->

{% endblock content%}

</body>

</html>

myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load static %}

!DOCTYPE html>
<html>
<body>
{% block content %}
{% include "myapp/base.html" %}

<div class="container nav-wrapper">
    <h4 align="center" class="green-text">{{name}}</h4>

    {% if sideways == True %}

    <div class="row">
            <div class="col s12">
                <div class="card black hoverable">
                    <div align="center">
                        <img src="data:image/png;base64,{{ photo }}" width = "500" height="auto">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div align="center" style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">
                    <p>{{message|linebreaks}}</p>
<!--                   <p style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">{{message|linebreaks}}</p>-->
                </div>
            </div>
        </div>
        <!--<div class="row">
            <div class="col s6">
                <div class="card black hoverable">
                    <div align="left">
                        <img src="data:image/png;base64,{{ photo }}" width = "500" height="auto">
                    </div>
                </div>
            </div>
            <div class="col s6">
                <div align="center" style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">
                    <p>{{message|linebreaks}}</p>
&lt;!&ndash;                    <p style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">{{message|linebreaks}}</p>&ndash;&gt;
                </div>
            </div>
        </div>-->

    {% else %}

        <div class="row">
            <div class="col s12">
                <div class="card black hoverable">
                    <div align="center">
                        <img src="data:image/png;base64,{{ photo }}" width = "500" height="auto">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div align="center" style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">
                    <p>{{message|linebreaks}}</p>
<!--                   <p style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">{{message|linebreaks}}</p>-->
                </div>
            </div>
        </div>

    {% endif %}
</div>
{% endblock content %}
</body>
</html>

myapp/templates/myapp/family.html
{% extends "myapp/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<body>
{% block content %}
{% include "myapp/base.html" %}
<div class="container nav-wrapper">
    <h4 class = "blue-text" align = "center">Time for some family time</h4>
</div>
<div class="container nav-wrapper">
    <div class="row">
        {% for f in family %}

            <div class="col s12 m4">
                <div class="card small">
                    <div class="card-image waves-effect waves-block waves-light" >
                        <a href = "{% url 'myapp:detail' f.0%}"><img class="activator" src={{f.1}}></a>
                    </div>
                    <div class="card-content">
                        <a href = "{% url 'myapp:detail' f.0%}"><span class="card-title activator grey-text text-darken-4">{{f.0}}</span></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}
</body>

</html>

myapp/templates/myapp/friends.html
{% extends "myapp/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<body>
{% block content %}
{% include "myapp/base.html" %}
<div class="container nav-wrapper">
    <h4 class = "green-text" align = "center">Wishes from your besties</h4>
</div>
<div class="container nav-wrapper">
    <div class="row">
        {% for f in friends %}
            <div class="col s12 m4">
                <div class="card small">
                    <div class="card-image waves-effect waves-block waves-light" >
                        <a href = "{% url 'myapp:detail' f.0%}"><img class="activator" src={{f.1}}></a>
                    </div>
                    <div class="card-content">
                        <a href = "{% url 'myapp:detail' f.0%}"><span class="card-title activator grey-text text-darken-4">{{f.0}}</span></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}
</body>

</html>

myapp/templates/myapp/home.html
{% extends "myapp/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<body>
{% block content %}
{% include "myapp/base.html" %}

<!--<div class="container nav-wrapper">-->

    <div class="row">
        <div class="col s4">
            <div style="float:left; ">
                <img height="550" class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
        <div class="col s4">
            <center>
                <img width="500" alt="centered image" src="{% static 'myapp/images/Prerna.png' %}">
            </center>
        </div>

        <div class="col s4">
            <div style="float:right; ">
                <img height="550" class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s2">
            <div style="float:left; ">
                <img class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
        <div class="col s2">
            <div style="float:left; ">
                <img class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
        <div class="col s2">
            <div style="float:left; ">
                <img class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>

        <div class="col s2">
            <div style="float:right; ">
                <img class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
        <div class="col s2">
            <div style="float:right; ">
                <img class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
                <div class="col s2">
            <div style="float:right; ">
                <img class="materialboxed" style="cursor:default"
                     src="{% static 'myapp/images/hb3.gif' %}">
            </div>
        </div>
    </div>
<!--</div>-->
<!--<audio autoplay>
  <source src="{% static 'myapp/media/H2.mp3' %}">
</audio>-->

<!--    <div style="width:1200px">

        <div style="float:left; ">
            <img class="materialboxed" width="450" height="550" style="cursor:default" src="{% static 'myapp/images/main4.png' %}">
        </div>
        <div style="float:right;">
            <span style="cursor:default"></span>
            <img class="materialboxed" width="450" height="550" style="cursor:default" src="{% static 'myapp/images/main.png' %}">
        </div>

        <div style="float:left;">
            <img class="materialboxed" width="450" style="cursor:default" src="{% static 'myapp/images/hb3.gif' %}">
        </div>
        <div style="float:right;">
            <img class="materialboxed" width="450" style="cursor:default" src="{% static 'myapp/images/hb3.gif' %}">
        </div>
    </div>
</div>-->


{% endblock %}
</body>

</html>

myapp/templates/myapp/lovelies.html
{% extends "myapp/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<body>
{% block content %}
{% include "myapp/base.html" %}
<div class="container nav-wrapper">
    <h4 class = "blue-text" align = "center">From your lovelies.....</h4>
</div>
<div class="container nav-wrapper">
    <div class="row">
        {% for l in lovelies %}

            <div class="col s12 m4">
                <div class="card small">
                    <div class="card-image waves-effect waves-block waves-light" >
                        <a href = "{% url 'myapp:detail' l.0%}"><img class="activator" src={{l.1}}></a>
                    </div>
                    <div class="card-content">
                        <a href = "{% url 'myapp:detail' l.0%}"><span class="card-title activator grey-text text-darken-4">{{l.0}}</span></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}
</body>

</html>

myapp/templates/myapp/newsearchfound.html
{% extends "myapp/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>

<body>
{% block content %}
{% include "myapp/base.html" %}
<div class="container nav-wrapper">
    {% if length == 1 %}
        <h4 class = "green-text" align = "center"> {{length}} entry found</h4>
    {% else %}
        <h4 class = "green-text" align = "center"> {{length}} entries found</h4>
    {% endif %}
</div>
<div class="container nav-wrapper">
    <div class="row">
        {% for l in displaylist %}
            <div class="col s12 m4">
                <div class="card small">
                    <div class="card-image waves-effect waves-block waves-light" >
                        <a href = "{% url 'myapp:detail' l.0%}"><img class="activator" src={{l.1}}></a>
                    </div>
                    <div class="card-content">
                        <a href = "{% url 'myapp:detail' l.0%}"><span class="card-title activator grey-text text-darken-4">{{l.0}}</span></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}
</body>

</html>

myapp/templates/myapp/searchfound.html
{% extends "myapp/base.html" %}
{% load static %}

!DOCTYPE html>
<html>
<body>
{% block content %}
{% include "myapp/base.html" %}

<div class="container nav-wrapper">
    <h4 align="center" class="green-text">{{name}}</h4>

    <div class="row">
        <div class="col s6">
            <div class="card black hoverable">
                <div align="left">
                    <img src="data:image/png;base64,{{ photo }}" width="600">
                </div>
            </div>
        </div>
        <div class="col s6">

                <div align="center" style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">
                    <p>{{message|linebreaks}}</p>
<!--                    <p style="font-size:24px; color:white; font-family:Helvetica Neue; font-style:italic">{{message|linebreaks}}</p>-->
                </div>

        </div>

    </div>
</div>
{% endblock content %}
</body>
</html>

myapp/templates/myapp/videodetail.html
{% extends "myapp/base.html" %}
{% load static %}

!DOCTYPE html>
<html>
<body>
{% block content %}
{% include "myapp/base.html" %}

<div class="container nav-wrapper">
    <h4 align="center" class="green-text">{{name}}</h4>

    {% if video_present == True %}
    <div class="row">
            <div class="col s12">
                <div class="card black hoverable">
                    <div align="center">
                        <video class='center' width='400' controls>
                            <source src="{{video_path}}">
                        </video>
                    </div>
                </div>
            </div>
    </div>

    {% else %}
        <div class="row">
            <div class="col s12">
                <div class="card black hoverable">
                    <div align="center">
                        <img src="data:image/png;base64,{{ photo }}" width = "700" height="auto">
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}
</body>
</html>